apiVersion: v1
kind: Pod
metadata:
  name: "creditcardpod"
  namespace: default
  labels:
    app: "creditcard"
    version: "1.0"
spec:
  containers:
  - name: creditcard
    image: "hemandhareddy/creditcard:1.0"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    port:
    - containerPort: 8082
      name: http
      protocal: TCP
    livenessProbe:
      httpGet:
        path: /creditcard/hello
        port: 8082
      initialDelaySeconds: 10
      timeoutSeconds: 15
    readinessProbe:
      httpGet:
        path: /creditcard/hello
        port: 8082
      initialDelaySeconds: 10
      timeoutSeconds: 15
    env:
    - name: java.username
      valueFrom:
        configMapKeyRef:
          name: creditcardconfigmap
          key: username
    - name: java.password
      valueFrom:
        configMapKeyRef:
          key: password
          name: creditcardconfigmap
    volumeMounts:
    - name: creditcardvolume
      mountPath: "/config"
      readOnly: true

  volumes:
  - name: creditcardvolume
    configMap:
      name: creditcardconfigmap
      items:
      - key: myapp.properties
        path: "myapp.properties"
