apiVersion: v1
kind: Pod
metadata:
  name: foodiespod
  labels:
    name: foodies
spec:
  containers:
  - name: foodies
    image: hemanadhareddy/creditcard:1.0
    ports:
    - name: tomcatport
      containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /data/fetch
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 10
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1000Mi"
    env:
    - name: username
      valueFrom:
        configMapKeyRef:
          name: creditcard-demo
          key: java.username
    - name: password
      valueFrom:
        configMapKeyRef:
          name: creditcard-demo
          key: java.password
    volumeMounts:
    - name: foodiesmyappconfigmapvolume
      mountPath: "/config"
      readOnly: true
  volumes:
  - name: foodiesmyappconfigmapvolume
    configMap:
      name: creditcard-demo
      items:
      - key: "myapp.properties"
        path: "myapp.properties"
