apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: hemanadhareddy/creditcard:1.0
    ports:
    - name: tomcatport
      containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: config-volume
      mountPath: /path/to/myapp.properties
      subPath: myapp.properties
  volumes:
  - name: config-volume
    configMap:
      name: creditcard-configmap
